import Head from 'next/head'
import HomeContainer from '../containers/home'
import DefaultLayout from '../layouts/default'
import { useAppSelector } from '../redux'
import { selectCount } from '../redux/test'
export default function HomePage() {
  const count = useAppSelector(selectCount)

  return (
    <>
      <Head>
        <title>Home App {count}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HomeContainer />
    </>
  )
}

HomePage.getLayout = (page: React.ReactElement) => {
  return <DefaultLayout>{page}</DefaultLayout>
}
